### ISSUE TITLE
Needs update to work in Laravel > 5.3

### ISSUE THREAD

**Issue by emmettculley** [daftspunk/laravel-config-writer#15]
I have a fix that now works in Laravel 5.5.  Will push pull request.

**Comment by emmettculley** [comment]
Unfortunately git hub pull requests are broken.  I forked master then made my changes in a branch named update.  Pushed the committed code to the fork.  But when clicking on new pull request I get an empty page and nothing further happens.

What am I doing wrong.

Note this is my first time attempting to contribute on git hub.

**Comment by daftspunk** [comment]
Should work now
