### ISSUE TITLE
Update for Laravel 5.4 and greater and Lumen support

### ISSUE THREAD

**Issue by tekreme73** [daftspunk/laravel-config-writer#16]
Due to inactivity, I have forked this project to resolve some main issues it has:

- For #13 & #15: Compatibility with Laravel 5.4 and greater,
- Add Lumen provider support,
- Add PHP explicit typings (PHP 7),
- Fix regex 'non-greedy' search,
- Update Readme.md for usage.

If you want this update, you can check this repository https://github.com/tekreme73/laravel-config-writer

I have changed the architecture and rename the namespace, that's why I'm not doing a PR, sorry for that.
If you want to, I can make a PR but it will need some commit to remove my 'Tekreme73' namespace...

**Comment by daftspunk** [comment]
You could always submit a pull request

**Comment by tekreme73** [comment]
Pull Request created #17

**Comment by tekreme73** [comment]
PR #18 removes the 'Tekreme73' namespace

**Comment by daftspunk** [comment]
Good stuff

Thanks
