### ISSUE TITLE
Is Laravel 5.8 supported?

### ISSUE THREAD

**Issue by rottndandie** [daftspunk/laravel-config-writer#23]
I'm running Laravel 5.8.27 and installed illuminate/config, which gave me version 5.8. When I tried installing your config writer, I got this error:

> $ composer require "daftspunk/laravel-config-writer"
> Using version ^1.0 for daftspunk/laravel-config-writer
> ./composer.json has been updated
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - don't install illuminate/config 4.2.x-dev|don't install laravel/framework v5.8.27
>     - don't install illuminate/config 4.2.x-dev|remove laravel/framework v5.8.27
>     - don't install illuminate/config 4.2.x-dev|don't install laravel/framework v5.8.27
>     - daftspunk/laravel-config-writer v1.0 requires illuminate/config 4.2.x -> satisfiable by illuminate/config[4.2.x-dev].
>     - Installation request for daftspunk/laravel-config-writer ^1.0 -> satisfiable by daftspunk/laravel-config-writer[v1.0].
>     - Installation request for laravel/framework (locked at v5.8.27, required as 5.8.*) -> satisfiable by laravel/framework[v5.8.27].
> 
> 
> Installation failed, reverting ./composer.json to its original content.

Did I do something wrong? Any advice? Thank you!

**Comment by IlyasDeckers** [comment]
I created a pull request for this issue, but the repo seems abandoned.
You can pull this repo and update `illuminate/config` to 6.0 or above in the composer file.

**Comment by daftspunk** [comment]
Should work in v1.1
