### ISSUE TITLE
Laravel v9 Installation Error

### ISSUE THREAD

**Issue by Soltee** [daftspunk/laravel-config-writer#26]
Installation on Laravel 9

ERROR!!!
Could not find a matching version of package daftspunk/laravel-config-writer. Check the package spelling, your version constraint and that the package is availabl     e in a stability which matches your minimum-stability (dev).

**Comment by EmilioBravo** [comment]
Same here, any solution to this?

**Comment by daftspunk** [comment]
Its published, try now
