### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by vladrusu** [daftspunk/laravel-config-writer#5]
Please provide installation instructions in the readme.

Thanks!

**Comment by illuminate3** [comment]
I would appreciate to know too.
Thanks

**Comment by daftspunk** [comment]
The readme covers this currently.

https://github.com/daftspunk/laravel-config-writer#usage-instructions

**Comment by illuminate3** [comment]
This is error I get when trying to install with composer:

```
  Problem 1
    - The requested package daftspunk/laravel-config-writer could not be found in any version, there may be a typo in the package name.
```

If I use the name from the composer.json file

```
  Problem 1
    - Installation request for october/config dev-master -> satisfiable by october/config[dev-master].
    - october/config dev-master requires october/support ~1.0 -> no matching package found.
```

**Comment by odera89** [comment]
The installation description is missing. Please provide them.

THanks
