### ISSUE TITLE
Laravel 5

### ISSUE THREAD

**Issue by coding-sunshine** [daftspunk/laravel-config-writer#7]
Any luck making this work with laravel 5?

**Comment by nWidart** [comment]
:+1: 
Would appreciate a laravel 5 compatible version.

**Comment by scottconnerly** [comment]
+1

**Comment by kirkaracha** [comment]
i++

**Comment by daftspunk** [comment]
The library itself is sound, can someone submit a PR to make the API work with IoC in Laravel 5.x?

**Comment by nWidart** [comment]
Hm in laravel 5 a lot of things don't work from this package. Lot's of namespaces have changes, classes not existent. etc. It's not as simple as just changing laravel 5 version in composer.json file.

**Comment by tuytoosh** [comment]
[InvalidArgumentException]
  Could not find package daftspunk/laravel-config-writer at any version for your minimum-stability (stable). Check the package spelling or
   your minimum-stability

**Comment by gianadrias** [comment]
attrox how do I include this in my laravel project ? thanks

**Comment by gianadrias** [comment]
attrox how do I include this in my laravel project ? thanks

**Comment by attrox** [comment]
You can go inside the vendor folder and clone my forked branch there. Run `composer dump-autoload`.

Modify config/app.php and add `October\Rain\Config\ConfigServiceProvider::class,` inside the `providers` array.

You should be able to do `Config::write()` or `app('config')->write()` after that.

**Comment by daftspunk** [comment]
Should work now
