### ISSUE TITLE
How to install this package on L5?

### ISSUE THREAD

**Issue by odera89** [daftspunk/laravel-config-writer#9]
What write in the composer.json?

Thanks,
Hunor

**Comment by vkshrivastva** [comment]
Need to add this composer require setting: 
"illuminate/config": "~5.0."

**Comment by rustem-art** [comment]
Class 'October\Rain\Config\ConfigServiceProvider' not found

**Comment by sunnyjayjay** [comment]
Same problem for me

**Comment by KWCG** [comment]
Same problem for me

**Comment by daftspunk** [comment]
This is a Laravel 4.2 package. Sorry guys.
